# First Element wise array

In [1]:
import numpy as np

In [2]:
x=np.array([10,10,9,6,10])

In [3]:
np.sqrt(x)

array([3.16227766, 3.16227766, 3.        , 2.44948974, 3.16227766])

In [4]:
np.power(x,2)

array([100, 100,  81,  36, 100], dtype=int32)

In [5]:
y=[7.3,3,8,-9,10]

In [6]:
np.maximum(x,y)

array([10., 10.,  9.,  6., 10.])

In [9]:
np.abs(x)

array([10, 10,  9,  6, 10])

In [10]:
np.square(x)

array([100, 100,  81,  36, 100], dtype=int32)

In [11]:
np.exp(x)

array([22026.46579481, 22026.46579481,  8103.08392758,   403.42879349,
       22026.46579481])

In [14]:
np.log(x)

array([2.30258509, 2.30258509, 2.19722458, 1.79175947, 2.30258509])

In [16]:
np.log10(x)

array([1.        , 1.        , 0.95424251, 0.77815125, 1.        ])

In [17]:
np.log2(x)

array([3.32192809, 3.32192809, 3.169925  , 2.5849625 , 3.32192809])

In [18]:
np.log1p(x)

array([2.39789527, 2.39789527, 2.30258509, 1.94591015, 2.39789527])

In [19]:
np.sign(x)

array([1, 1, 1, 1, 1])

In [20]:
np.ceil(x)

array([10., 10.,  9.,  6., 10.])

In [21]:
np.floor(x)

array([10., 10.,  9.,  6., 10.])