In [1]:
import numpy as np

In [2]:
x=np.array([-10.1,10,9.1,8,9])

In [4]:
x.mean()

5.2

In [5]:
x.cumsum()

array([-10.1,  -0.1,   9. ,  17. ,  26. ])

In [6]:
x.cumprod()

array([-1.01000e+01, -1.01000e+02, -9.19100e+02, -7.35280e+03,
       -6.61752e+04])

In [7]:
y=x>6

In [8]:
y

array([False,  True,  True,  True,  True])

In [9]:
x.sum()

26.0

In [10]:
x.any()

True

In [11]:
x.all()

True

In [12]:
y.all()

False

In [13]:
y.sum()

4

In [16]:
x.sort()

In [17]:
x

array([-10.1,   8. ,   9. ,   9.1,  10. ])

In [20]:
np.unique(x)

array([-10.1,   8. ,   9. ,   9.1,  10. ])