In [1]:
import numpy as np

In [2]:
np.random.seed(7)

In [3]:
np.random.uniform(size=(3,3))

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898]])

In [6]:
np.random.gamma(3)

7.5312030446658635

In [7]:
np.random.normal(size=(4,4))

array([[-1.32805048e-03, -6.25428974e-01, -1.71548261e-01,
         5.05299374e-01],
       [-2.61356415e-01, -2.42749079e-01, -1.45324141e+00,
         5.54580312e-01],
       [ 1.23880905e-01,  2.74459924e-01, -1.52652453e+00,
         1.65069969e+00],
       [ 1.54335535e-01, -3.87139943e-01,  2.02907222e+00,
        -4.53860299e-02]])

In [9]:
x=np.ones((4,4))

In [10]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
x[1:-1,1:-1]=0

In [12]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])