In [1]:
import numpy as np

In [10]:
x=np.random.randn(4,5)

In [11]:
x

array([[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,  1.16624333],
       [ 0.78224371, -1.08994875, -1.31437148,  0.35554739, -0.479744  ],
       [ 1.76045424,  0.15464832,  0.66094004,  1.18919426, -1.01874174],
       [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013, -1.42322262]])

In [12]:
x.reshape((2,2,5))

array([[[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,
          1.16624333],
        [ 0.78224371, -1.08994875, -1.31437148,  0.35554739,
         -0.479744  ]],

       [[ 1.76045424,  0.15464832,  0.66094004,  1.18919426,
         -1.01874174],
        [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013,
         -1.42322262]]])

In [16]:
x.reshape((2,2,5))

array([[[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,
          1.16624333],
        [ 0.78224371, -1.08994875, -1.31437148,  0.35554739,
         -0.479744  ]],

       [[ 1.76045424,  0.15464832,  0.66094004,  1.18919426,
         -1.01874174],
        [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013,
         -1.42322262]]])

In [17]:
x.reshape((2,2,5),order='F')

array([[[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,
          1.16624333],
        [ 1.76045424,  0.15464832,  0.66094004,  1.18919426,
         -1.01874174]],

       [[ 0.78224371, -1.08994875, -1.31437148,  0.35554739,
         -0.479744  ],
        [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013,
         -1.42322262]]])

In [19]:
x.reshape((2,2,5),order='c')

array([[[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,
          1.16624333],
        [ 0.78224371, -1.08994875, -1.31437148,  0.35554739,
         -0.479744  ]],

       [[ 1.76045424,  0.15464832,  0.66094004,  1.18919426,
         -1.01874174],
        [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013,
         -1.42322262]]])

In [20]:
x

array([[-1.0805853 , -0.88994506,  0.14517676, -0.58814373,  1.16624333],
       [ 0.78224371, -1.08994875, -1.31437148,  0.35554739, -0.479744  ],
       [ 1.76045424,  0.15464832,  0.66094004,  1.18919426, -1.01874174],
       [ 2.30560387, -0.7864882 , -0.63217446,  0.77684013, -1.42322262]])

In [21]:
x.ravel()

array([-1.0805853 , -0.88994506,  0.14517676, -0.58814373,  1.16624333,
        0.78224371, -1.08994875, -1.31437148,  0.35554739, -0.479744  ,
        1.76045424,  0.15464832,  0.66094004,  1.18919426, -1.01874174,
        2.30560387, -0.7864882 , -0.63217446,  0.77684013, -1.42322262])

In [22]:
x.flatten()

array([-1.0805853 , -0.88994506,  0.14517676, -0.58814373,  1.16624333,
        0.78224371, -1.08994875, -1.31437148,  0.35554739, -0.479744  ,
        1.76045424,  0.15464832,  0.66094004,  1.18919426, -1.01874174,
        2.30560387, -0.7864882 , -0.63217446,  0.77684013, -1.42322262])