In [1]:
import numpy as np

a=np.ones((7,7))

In [2]:
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
a[1:-1,1:-1]=0

In [30]:
a

array([[1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.]])

In [37]:
x=np.ones((8,8))

In [39]:
x[1:-1,1:-1]=0

In [40]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
x.mean()

0.4375

In [42]:
x.sum()

28.0

In [43]:
x.cumsum()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  9.,  9.,  9.,  9.,
        9.,  9., 10., 11., 11., 11., 11., 11., 11., 11., 12., 13., 13.,
       13., 13., 13., 13., 13., 14., 15., 15., 15., 15., 15., 15., 15.,
       16., 17., 17., 17., 17., 17., 17., 17., 18., 19., 19., 19., 19.,
       19., 19., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.])

In [44]:
x.cumprod()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
x.any()

True

In [46]:
x.all()

False

In [47]:
x.sort()

In [48]:
np.unique(x)

array([0., 1.])

In [49]:
np.save('pract.npy',x)

In [50]:
np.load('pract.npy')

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.savez('pract1.npz',x,x)

In [61]:
a=np.load('pract1.npz')

In [63]:
a['x']

KeyError: 'x is not a file in the archive'

In [64]:
x=np.random.randn(3,2)
y=np.random.randn(2,3)

In [65]:
np.dot(x,y)

array([[ 0.5942875 , -2.76940688,  1.12910111],
       [-0.31670357,  2.71110344, -0.27817125],
       [ 2.60141012, -3.29396818,  7.25493394]])

In [66]:
x.transpose()

array([[-0.72854578,  0.37885013, -3.2563018 ],
       [ 1.53076787, -1.54207938,  1.50953328]])